Repository wecoach-ai/DatasetHandler, pull requests merged in 2024-07, with the labels that each got.

#9 Adds docstrings
  entrypoint.py
  src/download.py
  src/extract.py
Labels: documentation

#13 Add cleanup option in download command
  README.md
  entrypoint.py
  src/download.py
Labels: enhancement

#14 Adds check for mypy
  .github/workflows/ci.yml
  src/download.py
  src/extract.py
Labels: enhancement

#15 Adds TODO items
  README.md
Labels: documentation

#16 Adds poetry for dependency management
  .github/workflows/ci.yml
  README.md
  bin/background.sh
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#17 Updates pyproject.toml to include config for tooling
  .github/workflows/ci.yml
  README.md
  entrypoint.py
  poetry.lock
  pyproject.toml
  src/download.py
  src/extract.py
Labels: enhancement

#18 Add Unit Testing in CI
  .github/workflows/ci.yml
  .gitignore
  README.md
  poetry.lock
  pyproject.toml
  src/extract.py
  tests/__init__.py
  tests/test_download.py
Labels: enhancement

#20 Fixes CD Pipeline
  .github/workflows/cd.yml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_download.py
Labels: bug

#21 Fixes failing CD pipeline
  .github/workflows/cd.yml
Labels: bug

#22 Increases unit test coverage
  README.md
  pyproject.toml
  src/download.py
  tests/conftest.py
  tests/test_download.py
Labels: good first issue
